Hw02 express
dmytrosem-tech/nodejs-homework-dmytro pull request #1
Opened 2021-12-20 15:26 UTC by dmytrosem-tech

Вроде бы сделал все)

2021-12-20 21:06 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => {
почему асинхронная функция?

2021-12-20 21:08 UTC, KirillKulakow commented on model/index.js
> +  if (name && email && phone) {
зачем проверка если у тебя есть схема JOI?

2021-12-20 21:08 UTC, KirillKulakow requested changes
need fix

2021-12-21 08:14 UTC, dmytrosem-tech commented on model/index.js
> +const listContacts = async () => {
Согласен.

2021-12-21 08:14 UTC, dmytrosem-tech commented on model/index.js
> +  if (name && email && phone) {
Согласен полностью, уже убрал)

2021-12-21 08:17 UTC, dmytrosem-tech commented
Fix done.

2021-12-21 20:15 UTC, KirillKulakow approved these changes

2021-12-24 07:59 UTC, merged